Repository TempLLO/templlo-booking-2025, pull requests merged in 2025-01, with the labels that each got.

#26 User, Review 프로젝트 세팅 및 CI 파이프라인 적용
  com.templlo.service.review/.gitattributes
  com.templlo.service.review/.gitignore
  com.templlo.service.review/build.gradle
  com.templlo.service.review/gradle/wrapper/gradle-wrapper.jar
  com.templlo.service.review/gradle/wrapper/gradle-wrapper.properties
  com.templlo.service.review/gradlew
  com.templlo.service.review/gradlew.bat
  com.templlo.service.review/settings.gradle
  com.templlo.service.review/src/main/java/com/templlo/service/review/ReviewApplication.java
  com.templlo.service.review/src/main/resources/application.yml
  com.templlo.service.review/src/test/java/com/templlo/service/review/ReviewApplicationTests.java
  com.templlo.service.user/.gitattributes
  com.templlo.service.user/.gitignore
  com.templlo.service.user/build.gradle
  com.templlo.service.user/gradle/wrapper/gradle-wrapper.jar
  com.templlo.service.user/gradle/wrapper/gradle-wrapper.properties
  com.templlo.service.user/gradlew
  com.templlo.service.user/gradlew.bat
  com.templlo.service.user/settings.gradle
  com.templlo.service.user/src/main/java/com/templlo/service/user/UserApplication.java
  com.templlo.service.user/src/main/resources/application.yml
  com.templlo.service.user/src/test/java/com/templlo/service/user/UserApplicationTests.java
  gateway/gradle/wrapper/gradle-wrapper.jar
  gateway/gradle/wrapper/gradle-wrapper.properties
  gateway/gradlew
  gateway/gradlew.bat
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
Labels: ⚙ Setting

#28 프로모션 기능 구현 및 API 추가
  com.templlo.service.promotion/.gitattributes
  com.templlo.service.promotion/.gitignore
  com.templlo.service.promotion/build.gradle
  com.templlo.service.promotion/gradle/wrapper/gradle-wrapper.jar
  com.templlo.service.promotion/gradle/wrapper/gradle-wrapper.properties
  com.templlo.service.promotion/gradlew
  com.templlo.service.promotion/gradlew.bat
  com.templlo.service.promotion/settings.gradle
  com.templlo.service.promotion/src/main/java/com/templlo/service/promotion/PromotionApplication.java
  com.templlo.service.promotion/src/main/java/com/templlo/service/promotion/controller/PromotionController.java
  com.templlo.service.promotion/src/main/java/com/templlo/service/promotion/dto/PromotionDetailResponseDto.java
  com.templlo.service.promotion/src/main/java/com/templlo/service/promotion/dto/PromotionRequestDto.java
  com.templlo.service.promotion/src/main/java/com/templlo/service/promotion/dto/PromotionResponseDto.java
  com.templlo.service.promotion/src/main/java/com/templlo/service/promotion/dto/PromotionUpdateDto.java
  com.templlo.service.promotion/src/main/java/com/templlo/service/promotion/entity/Promotion.java
  com.templlo.service.promotion/src/main/java/com/templlo/service/promotion/repository/PromotionRepository.java
  com.templlo.service.promotion/src/main/java/com/templlo/service/promotion/service/PromotionService.java
  com.templlo.service.promotion/src/main/resources/application.yaml
  com.templlo.service.promotion/src/main/resources/http/promotion-request.http
  com.templlo.service.promotion/src/test/java/com/templlo/service/promotion/PromotionApplicationTests.java
  com.templlo.service.promotion/src/test/resources/application.yml
  gateway/.gitattributes
  gateway/.gitignore
  server/.gitattributes
  server/.gitignore
Labels: ⚙ Setting, ✨ Feature

#50 [Feat/34/program] 프로그램 update 기능 구현
  com.templlo.service.program/.gitattributes
  com.templlo.service.program/.gitignore
  com.templlo.service.program/build.gradle
  com.templlo.service.program/gradle/wrapper/gradle-wrapper.jar
  com.templlo.service.program/gradle/wrapper/gradle-wrapper.properties
  com.templlo.service.program/gradlew
  com.templlo.service.program/gradlew.bat
  com.templlo.service.program/settings.gradle
  com.templlo.service.program/src/main/java/com/templlo/service/program/ProgramApplication.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/auditor/AuditorAwareImpl.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/auditor/AuditorProvider.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/auditor/BaseEntity.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/config/JpaConfig.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/config/QueryDslConfig.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/controller/ProgramController.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/dto/request/CreateProgramRequest.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/dto/request/UpdateProgramRequest.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/dto/response/BlindDateProgramResponse.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/dto/response/DetailProgramResponse.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/dto/response/SimpleProgramResponse.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/dto/response/TempleStayProgramResponse.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/entity/BlindDateInfo.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/entity/Program.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/entity/ProgramGenderStatus.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/entity/ProgramStatus.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/entity/ProgramType.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/entity/TempleStayDailyInfo.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/exception/ProgramException.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/exception/ProgramStatusCode.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/exception/ValidExceptionHandler.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/global/common/exception/BaseException.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/global/common/exception/GlobalExceptionHandler.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/global/common/response/ApiResponse.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/global/common/response/BasicStatusCode.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/global/common/response/StatusCode.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/repository/JpaProgramRepository.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/repository/JpaTempleStayDailyInfoRepository.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/repository/QueryProgramRepository.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/service/ProgramService.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/util/PagingUtil.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/validation/CreateProgramRequestValidator.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/validation/ValidCreateProgramRequest.java
  com.templlo.service.program/src/main/resources/application.yml
  com.templlo.service.program/src/main/resources/http/program-request.http
  com.templlo.service.program/src/test/java/com/templlo/service/program/ProgramApplicationTests.java
  com.templlo.service.program/src/test/resources/application.yml
Labels: ✨ Feature

#43 [Feat/34/program] 프로그램 create 기능 구현
  com.templlo.service.program/src/main/java/com/templlo/service/program/validation/CreateProgramRequestValidator.java
Labels: ✨ Feature

#53 [Feat/30/create reservation] 예약 생성 기능 구현
  com.templlo.service.reservation/build.gradle
  com.templlo.service.reservation/docker-compose.yml
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/domain/reservation/controller/CreateReservationController.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/domain/reservation/controller/ReservationCreateController.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/domain/reservation/controller/exception/ReservationStatusCode.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/domain/reservation/controller/model/request/CouponUsedType.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/domain/reservation/controller/model/request/CreateReservationReq.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/domain/reservation/controller/model/response/CreateReservationRes.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/domain/reservation/domain/PaymentStatus.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/domain/reservation/domain/PaymentType.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/domain/reservation/domain/Reservation.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/domain/reservation/domain/ReservationGenderType.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/domain/reservation/domain/ReservationStatus.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/domain/reservation/repository/ReservationRepository.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/domain/reservation/service/ReservationCommandService.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/domain/reservation/service/ReservationConsumeService.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/domain/reservation/service/model/consume/ConsumerTopicGroupName.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/domain/reservation/service/model/consume/CreateReservationResultConsume.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/domain/reservation/service/model/consume/CreateReservationResultStatus.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/domain/reservation/service/model/produce/CreateReservationProduce.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/domain/reservation/service/model/produce/ProducerTopic.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/domain/temp/ConsumerTestService.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/domain/temp/KafkaTestController.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/domain/temp/TestController.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/domain/temp/TestReq.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/global/common/jpa/AuditorAwareImpl.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/global/common/jpa/BaseEntity.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/global/common/jpa/CustomAuditingEntityListener.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/global/config/ConsumerApplicationKafkaConfig.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/global/config/GsonConfig.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/global/config/ProducerApplicationKafkaConfig.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/global/config/WebSecurityConfig.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/global/security/CustomAuthenticationFilter.java
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/global/security/UserRole.java
  com.templlo.service.reservation/src/main/resources/application.yml
  com.templlo.service.reservation/src/main/resources/http/checker/HealthCheck.http
  com.templlo.service.reservation/src/main/resources/http/checker/KafkaTest.http
  com.templlo.service.reservation/src/main/resources/http/checker/Test.http
  com.templlo.service.reservation/src/main/resources/http/checker/health-check/HealthCheck.http
  com.templlo.service.reservation/src/main/resources/http/checker/test/NeedAuth.http
  com.templlo.service.reservation/src/main/resources/http/checker/test/ReservationException.http
  com.templlo.service.reservation/src/main/resources/http/checker/test/TestRoleMaster.http
  com.templlo.service.reservation/src/main/resources/http/checker/test/TestRoleTemple.http
  com.templlo.service.reservation/src/main/resources/http/checker/test/TestRoleUser.http
  com.templlo.service.reservation/src/main/resources/http/reservation/CreateReservation.http
  com.templlo.service.reservation/src/test/resources/application.yml
Labels: ✨ Feature

#54 [Feat/14/user-review] 유저, 리뷰 도메인 producer/consumer 서비스, 토큰 재발급 서비스 구현
  com.templlo.service.review/src/main/java/com/templlo/service/review/common/exception/ErrorCode.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/common/exception/GlobalExceptionHandler.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/common/exception/baseException/BaseException.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/common/exception/baseException/CustomBadRequestException.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/common/exception/baseException/CustomFeignException.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/common/exception/baseException/CustomForbiddenException.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/common/exception/baseException/DuplicatedReviewException.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/common/exception/baseException/ReviewNotFoundException.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/common/exception/baseException/UnauthorizedException.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/common/exception/baseException/UserNotFoundException.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/entity/Review.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/external/feignClient/CustomErrorDecoder.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/external/kafka/producer/ReviewEventProducer.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/external/kafka/producer/ReviewEventProducerImpl.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/external/kafka/producer/dto/ReviewCreatedEventDto.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/external/kafka/producer/dto/ReviewUpdatedEventDto.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/external/kafka/topic/ProducerTopic.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/service/CreateReviewService.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/service/UpdateReviewService.java
  com.templlo.service.review/src/main/resources/application.yml
  com.templlo.service.review/src/main/resources/memberReview.http
  com.templlo.service.review/src/test/resources/application.yml
  com.templlo.service.user/build.gradle
  com.templlo.service.user/src/main/java/com/templlo/service/user/common/exception/BaseException.java
  com.templlo.service.user/src/main/java/com/templlo/service/user/common/exception/GlobalExceptionHandler.java
  com.templlo.service.user/src/main/java/com/templlo/service/user/common/response/BasicStatusCode.java
  com.templlo.service.user/src/main/java/com/templlo/service/user/controller/AuthController.java
  com.templlo.service.user/src/main/java/com/templlo/service/user/controller/UserController.java
  com.templlo.service.user/src/main/java/com/templlo/service/user/entity/User.java
  com.templlo.service.user/src/main/java/com/templlo/service/user/external/kafka/config/KafkaConsumerConfig.java
  com.templlo.service.user/src/main/java/com/templlo/service/user/external/kafka/config/KafkaProducerConfig.java
  com.templlo.service.user/src/main/java/com/templlo/service/user/external/kafka/consumer/EventListener.java
  com.templlo.service.user/src/main/java/com/templlo/service/user/external/kafka/consumer/dto/ReviewCreatedEventDto.java
  com.templlo.service.user/src/main/java/com/templlo/service/user/external/kafka/producer/UserEventProducer.java
  com.templlo.service.user/src/main/java/com/templlo/service/user/external/kafka/producer/UserEventProducerImpl.java
  com.templlo.service.user/src/main/java/com/templlo/service/user/external/kafka/producer/dto/ReviewRewardEventDto.java
  com.templlo.service.user/src/main/java/com/templlo/service/user/external/kafka/topic/ConsumerTopic.java
  com.templlo.service.user/src/main/java/com/templlo/service/user/external/kafka/topic/ProducerTopic.java
  com.templlo.service.user/src/main/java/com/templlo/service/user/service/AuthService.java
  com.templlo.service.user/src/main/java/com/templlo/service/user/service/CreateUserService.java
  com.templlo.service.user/src/main/java/com/templlo/service/user/service/ReadUserService.java
  com.templlo.service.user/src/main/java/com/templlo/service/user/service/UpdateUserService.java
  com.templlo.service.user/src/main/resources/application.yml
  com.templlo.service.user/src/test/resources/application.yml
  gateway/src/main/java/com/templlo/gateway/filter/AuthenticationFilter.java
  gateway/src/main/java/com/templlo/gateway/util/JwtValidType.java
Labels: ✨ Feature

#67 [Feat/66/program update program schedule add program reivew count]
  com.templlo.service.program/src/main/java/com/templlo/service/program/controller/ProgramController.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/dto/request/CreateProgramRequest.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/dto/request/UpdateProgramScheduleRequest.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/dto/response/BlindDateScheduleResponse.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/dto/response/ProgramsByTempleResponse.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/entity/BlindDateInfo.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/entity/Program.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/entity/TempleStayDailyInfo.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/exception/ProgramException.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/exception/ProgramStatusCode.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/feign/FeignAuthHeaderInterceptor.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/feign/TempleClient.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/global/common/response/ApiResponseAdvice.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/kafka/consumer/ReviewConsumer.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/kafka/message/review/ReviewCreateMessage.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/kafka/message/review/ReviewUpdateMessage.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/service/ProgramService.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/validation/CreateProgramRequestValidator.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/validation/UpdateProgramScheduleRequestValidator.java
  com.templlo.service.program/src/main/java/com/templlo/service/program/validation/ValidUpdateProgramScheduleRequest.java
  com.templlo.service.program/src/main/resources/http/program-request.http
  com.templlo.service.reservation/src/main/java/com/templlo/service/reservation/domain/reservation/service/model/consume/ConsumerTopicGroupName.java
Labels: ✨ Feature, 🔨 Refactor

#85 [Refact/#78/outbox review] 리뷰작성이벤트에 아웃박스 패턴 적용
  com.templlo.service.review/src/main/java/com/templlo/service/review/common/exception/ErrorCode.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/common/exception/baseException/JsonParsingException.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/entity/EventStatus.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/entity/ReviewOutbox.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/event/dto/ReviewCreatedEventDto.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/event/dto/ReviewUpdatedEventDto.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/event/external/config/KafkaProducerConfig.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/event/external/producer/ReviewExternalEventProducer.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/event/external/producer/ReviewExternalEventProducerImpl.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/event/internal/listener/ReviewInternalEventListener.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/event/internal/producer/ReviewInternalEventProducer.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/event/internal/producer/ReviewInternalEventProducerImpl.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/event/topic/ProducerTopic.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/external/kafka/producer/ReviewEventProducer.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/external/kafka/producer/ReviewEventProducerImpl.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/feignClient/CustomErrorDecoder.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/feignClient/client/ReservationClient.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/feignClient/client/UserClient.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/feignClient/config/FeignConfiguration.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/feignClient/dto/ReservationData.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/feignClient/dto/ReservationStatus.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/feignClient/dto/UserData.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/repository/ReviewOutboxRepository.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/service/CreateReviewService.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/service/ReadReviewService.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/service/ReviewOutboxService.java
  com.templlo.service.review/src/main/java/com/templlo/service/review/service/UpdateReviewService.java
Labels: 🔨 Refactor

#82 [Feature/79/promotion aop] AOP 생성 후 적용
  com.templlo.service.promotion/src/main/java/com/templlo/service/common/aop/DistributedLock.java
  com.templlo.service.promotion/src/main/java/com/templlo/service/common/aop/DistributedLockAspect.java
  com.templlo.service.promotion/src/main/java/com/templlo/service/common/aop/OutboxPublisher.java
  com.templlo.service.promotion/src/main/java/com/templlo/service/common/aop/OutboxPublisherAspect.java
  com.templlo.service.promotion/src/main/java/com/templlo/service/common/aop/RoleCheck.java
  com.templlo.service.promotion/src/main/java/com/templlo/service/common/aop/RoleCheckAspect.java
  com.templlo.service.promotion/src/main/java/com/templlo/service/coupon/helper/RedisPromotionHelper.java
  com.templlo.service.promotion/src/main/java/com/templlo/service/coupon/service/CouponService.java
  com.templlo.service.promotion/src/main/java/com/templlo/service/outbox/OutboxEvent.java
  com.templlo.service.promotion/src/main/java/com/templlo/service/outbox/OutboxEventListener.java
  com.templlo.service.promotion/src/main/java/com/templlo/service/outbox/entity/OutboxMessage.java
  com.templlo.service.promotion/src/main/java/com/templlo/service/outbox/repository/OutboxRepository.java
  com.templlo.service.promotion/src/main/java/com/templlo/service/promotion/entity/Promotion.java
  com.templlo.service.promotion/src/main/java/com/templlo/service/promotion/service/PromotionService.java
  com.templlo.service.promotion/src/main/resources/http/promotion-request.http
  com.templlo.service.promotion/src/test/java/com/templlo/service/promotion/CouponControllerTest.java
  com.templlo.service.promotion/src/test/java/com/templlo/service/promotion/CouponServiceTest.java
  com.templlo.service.promotion/src/test/java/com/templlo/service/promotion/PromotionServiceTest.java
  com.templlo.service.promotion/src/test/java/com/templlo/service/promotion/helper/MockRedisPromotionHelper.java
  com.templlo.service.promotion/src/test/java/com/templlo/service/promotion/helper/RedisPromotionHelper.java
  com.templlo.service.review/build.gradle
Labels: 🔨 Refactor

#86 [Refact/#80/elasticsearch] elasticsearch 동기화 로직 분리 및 circuit breaker 도입 / 기타 리팩토링
  com.templlo.service.temple/build.gradle
  com.templlo.service.temple/src/main/java/com/templlo/service/temple/Service/TempleService.java
  com.templlo.service.temple/src/main/java/com/templlo/service/temple/common/response/ApiResponse.java
  com.templlo.service.temple/src/main/java/com/templlo/service/temple/common/response/ErrorPageResponse.java
  com.templlo.service.temple/src/main/java/com/templlo/service/temple/common/security/SecurityConfig.java
  com.templlo.service.temple/src/main/java/com/templlo/service/temple/config/CacheConfig.java
  com.templlo.service.temple/src/main/java/com/templlo/service/temple/controller/TempleController.java
  com.templlo.service.temple/src/main/java/com/templlo/service/temple/dto/CreateTempleRequest.java
  com.templlo.service.temple/src/main/java/com/templlo/service/temple/dto/UpdateTempleRequest.java
  com.templlo.service.temple/src/main/java/com/templlo/service/temple/redis/RedisCacheEvictor.java
  com.templlo.service.temple/src/main/java/com/templlo/service/temple/repository/TempleRepositoryImpl.java
  com.templlo.service.temple/src/main/java/com/templlo/service/temple/service/TempleService.java
  com.templlo.service.temple/src/main/java/com/templlo/service/temple/service/elasticsearch/ElasticSearchSynchronizer.java
  com.templlo.service.temple/src/main/java/com/templlo/service/temple/service/elasticsearch/TempleSearchService.java
  com.templlo.service.temple/src/main/resources/application.yml
  com.templlo.service.temple/src/test/java/com/templlo/service/temple/TempleApplicationTests.java
  com.templlo.service.temple/src/test/java/com/templlo/service/temple/TempleControllerTest.java
  com.templlo.service.temple/src/test/resources/application.yml
  com.templlo.service.user/.gitignore
  com.templlo.service.user/build.gradle
Labels: 🔨 Refactor
